export const mockProducts = [
  {
    id: 1,
    name: "Heritage Strawberries",
    category: "Fruits",
    farm: "Nashik Orchards",
    distance: "12km away",
    price: "₹250",
    unit: "kg",
    freshness: 98,
    tags: ["98% Fresh", "Harvested Today"],
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuC2OlDrUBvTKax7v8kvU1k_tJeJTSkIXOKkW5y4LdeyGa5o_dK4lYAMnNTo5Rn4_6pLyvU4qHUHRtz8gMzCTbZfh9eslzyhberLHeYBjzScdEDqDaOIq6b2Yn8dKtYmg7-EtqleYWzqI43SaM-OBNLzkdyqAKpDZjMH02KSSpEqFSmK3if14pFW-M29mlEsUX1s9Kw4IjsoWwMafpfXe6rvDyg2rNTRpmVos_mG165uH0D_lHPGoByDELsYwmRWMOISLZJv8uChSjqB",
    description: "Sweet, juicy, and freshly picked organic strawberries from our heritage farm. Perfect for desserts or healthy snacking.",
    harvestDate: "Today, 6:00 AM",
    storageTip: "Store in a cool, dry place. Do not wash until ready to eat.",
    rating: 4.8,
    reviewsCount: 124
  },
  {
    id: 2,
    name: "Tuscan Curly Kale",
    category: "Vegetables",
    farm: "Green Valley Farms",
    distance: "8km away",
    price: "₹80",
    unit: "bunch",
    freshness: 92,
    tags: ["92% Fresh"],
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCM9cZYWfb5RjU3rhPFLpoRa9w8aUdffuLEzNVkIRynuKUVKP4M5KO6PffDsTrj5m_P7BShLW2e5iH88hMBJKT6ure8futBAJl14ey5fl0ztWFLRatBCIVdvx19D1HvhHUFxsBAdRxomibjQsFFnfq7EvSr_leEI6k4Qo5v3AC8CH0yRhK8kQ7mB2PH8Bn6z9S_gyixHMP8JLTytjyNqTqC2AAkCCJp-hzGy_OH_0JEN0o9Ti8GoEtVKfqWd72wrdgVU3z6EJ0y-Yyz",
    description: "Nutrient-dense, crisp curly kale. Excellent for salads, smoothies, or baking into healthy chips.",
    harvestDate: "Yesterday, 5:00 PM",
    storageTip: "Store unwashed in a plastic bag in the crisper drawer.",
    rating: 4.6,
    reviewsCount: 89
  },
  {
    id: 3,
    name: "Buffalo Mozzarella",
    category: "Dairy",
    farm: "Pure Pastures",
    distance: "18km away",
    price: "₹180",
    unit: "250g",
    freshness: 95,
    tags: ["95% Fresh", "New Batch"],
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCW3n0_xxmcdA-nIsuUmnssw3hv_wqjdm1R3Z8R64Sv99--2BjhVw2gz0uRjF-oqIT1VfYLeS2W3LcgnUvS5MTWjOlbW7lkaak99teQ7Up499ZJOy_vzd3MPZn4TlsawfLVj5JsFrM3wm1SN3JG85LQoVCaAwqRGkYzA3p9YcGB8HuCDsFWLHfcdYL40vru5crAOtRR6jT05T2SDmlp1-QvMccdmPSd3SY9EDIjpO0pzyzoUsvtcy7q_AteL7fM6aUmkk0RRBwMYqfi",
    description: "Handcrafted, artisanal buffalo mozzarella. Creamy, soft, and perfect for caprese salads or homemade pizzas.",
    harvestDate: "Prepared Today",
    storageTip: "Keep refrigerated in its liquid until use.",
    rating: 4.9,
    reviewsCount: 210
  },
  {
    id: 4,
    name: "Premium Hass Avocado",
    category: "Fruits",
    farm: "Hillside Groves",
    distance: "15km away",
    price: "₹120",
    unit: "unit",
    freshness: 62,
    tags: ["62% Ripening"],
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuBenbWIrerncQW5Jno0sxvEwEAUlqyV7JcJTL7vZIiklwBJPbZOmfNEh8RBnKGEZAtmFjvC4Gat93SnB-EwbIrbDRcGZtBPw3B72rji7iaIVrE2BAAroLs7AAtzZRDo3FB9Iywrvq2UsWWjqDq6kNpRJvaOa4HjtrwVcSJ8VaL1-xZLvJDY93bN49LFsEipAz4KLphGWO3nNfNhxwrdbLkfZdgQc8NnWROiVZX_81vhJgl8y3mAg5qWvjwG1qSLeOwQgs0ZMImXoEU1",
    description: "Rich, buttery Hass avocados. Currently ripening, will be perfectly ready to eat in 2-3 days.",
    harvestDate: "3 days ago",
    storageTip: "Leave at room temperature to ripen. Refrigerate once soft.",
    rating: 4.5,
    reviewsCount: 342
  },
  {
    id: 5,
    name: "Heirloom Tomato Mix",
    category: "Vegetables",
    farm: "Summer Ridge",
    distance: "22km away",
    price: "₹100",
    unit: "500g",
    freshness: 94,
    tags: ["94% Fresh"],
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuB5fMIXV40ssldSmjcDMMEjh0SBlR-ne1l6ydQNU7YtHem12evPscPIoXwRoGmHehKVNd-uwAkvs3LTIZfQ8ADyPe-2HcVVIMNGKE-UpRKHJjGl1dUUq-qNTcFvTnHznbWNbW9vlhY_ErQkHp_RU1RAfyGI5YGCuEJTRNP4Dp_0Z75FxZ3_2VH7vW2k6KX6odXsHPr1NWFy2Jp8SwMLFQyEdpGhq01EljNp__z42_4Ysk664aL1ItrdH1xS4v4PhmntpdAOsr4FuWWS",
    description: "A colorful mix of vine-ripened heirloom tomatoes. Incredibly flavorful and perfect for fresh salads.",
    harvestDate: "Yesterday, 6:00 AM",
    storageTip: "Store at room temperature away from direct sunlight.",
    rating: 4.7,
    reviewsCount: 156
  },
  {
    id: 6,
    name: "Wildflower Forest Honey",
    category: "Pantry",
    farm: "Bee Well Apiary",
    distance: "30km away",
    price: "₹350",
    unit: "jar",
    freshness: 100,
    tags: ["Pure Raw"],
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuDMbD7UsZGBlNLt5GnbDh2tTW0GVO4bvU6PsEG5oyBhkt5PNa4pFJ4lh2d4QYPTHfv6KycFn_Y6Ci8IbG6j5uAWu_-hQMKA1VqTVQ5hmc-ufvPN2Gl0KjGiqxTCEYaxtyzdEF94m46q4d_JWr4kBD-2AqOeoI9hpNDIARmLpb53u24rrqKAmABY1HwnRsJu36O9EsLqvJH7nm-WKERfbp9w98OqBb2jKL0kqbYXr1jiez4LbN9MeTZWQNW_g5zZMA0CeBquUEIZzCGj",
    description: "Raw, unfiltered wildflower honey straight from the comb. Contains natural pollen and enzymes.",
    harvestDate: "Last Week",
    storageTip: "Store at room temperature. If it crystallizes, warm gently.",
    rating: 4.9,
    reviewsCount: 521
  },
  {
    id: 7,
    name: "Organic Spring Onions",
    category: "Vegetables",
    farm: "Root & Sprout",
    distance: "5km away",
    price: "₹30",
    unit: "bunch",
    freshness: 99,
    tags: ["99% Fresh"],
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuDjOAVU6CTbbTCWmHAk1RYvus0ziGBX62LCKyvrYUfpUV8j0mJ1TWd85tNBkPBoIE5yPr_AD6IbqctDv0zk8dnUTjP7rnTUrzBsZIUPlE5dP37PTrlcd_TF9rQJz0xdCv_0RaNNubf1-XUoZ6riLwK5Ho_JkXsssooZRRHtLgp81Gg99p6hNUW9QC3NXPgt-u5eLuLu9BJRAgGlREAzPtSgMSTHPy3JblYGhv8rg8SJFXy_Om3CyLyvwn7F-F1O3Zli2POe7MV1dzGo",
    description: "Crisp, flavorful spring onions pulled from the soil this morning. Essential for garnishing and cooking.",
    harvestDate: "Today, 5:00 AM",
    storageTip: "Wrap in a damp paper towel and store in the crisper drawer.",
    rating: 4.5,
    reviewsCount: 67
  },
  {
    id: 8,
    name: "Heritage Sourdough",
    category: "Bakery",
    farm: "Grain & Fire",
    distance: "10km away",
    price: "₹120",
    unit: "loaf",
    freshness: 100,
    tags: ["Baked Today"],
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuAnPtvSyYTeiRDVLspZOFOig1d3RTm9VESnR5dMv7ATUePfDRbzbIb7mZkIxVWfHmcVO1FQN5zGm20iGGuLd8TaSm2yt1V5aiN59p7uXtQBbnmDVvrdLBrnI-k_G1DzasUHBL80HttbSN5bU50R3E-k8TDOjL2GL2sKyM7xWOtyjXm-RES_60SgI1FOj3OSHMQgKFoB9TAw_fW1n8bJk33VngZ-jTP3IkOr6p0BbOM4vcqSJuPx7w5AgHwXfx7ELVEupdZ5II5mbrhy",
    description: "Artisanal sourdough baked in a wood-fired oven using ancient grains. Crusty outside, chewy inside.",
    harvestDate: "Baked Today",
    storageTip: "Keep in a paper bag at room temperature. Freshen in oven before serving.",
    rating: 4.8,
    reviewsCount: 312
  }
];
